package com.jybar.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TblArticleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public TblArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTidIsNull() {
			addCriterion("tid is null");
			return (Criteria) this;
		}

		public Criteria andTidIsNotNull() {
			addCriterion("tid is not null");
			return (Criteria) this;
		}

		public Criteria andTidEqualTo(Long value) {
			addCriterion("tid =", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotEqualTo(Long value) {
			addCriterion("tid <>", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThan(Long value) {
			addCriterion("tid >", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThanOrEqualTo(Long value) {
			addCriterion("tid >=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThan(Long value) {
			addCriterion("tid <", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThanOrEqualTo(Long value) {
			addCriterion("tid <=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidIn(List<Long> values) {
			addCriterion("tid in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotIn(List<Long> values) {
			addCriterion("tid not in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidBetween(Long value1, Long value2) {
			addCriterion("tid between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotBetween(Long value1, Long value2) {
			addCriterion("tid not between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andAtitleIsNull() {
			addCriterion("aTitle is null");
			return (Criteria) this;
		}

		public Criteria andAtitleIsNotNull() {
			addCriterion("aTitle is not null");
			return (Criteria) this;
		}

		public Criteria andAtitleEqualTo(String value) {
			addCriterion("aTitle =", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleNotEqualTo(String value) {
			addCriterion("aTitle <>", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleGreaterThan(String value) {
			addCriterion("aTitle >", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleGreaterThanOrEqualTo(String value) {
			addCriterion("aTitle >=", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleLessThan(String value) {
			addCriterion("aTitle <", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleLessThanOrEqualTo(String value) {
			addCriterion("aTitle <=", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleLike(String value) {
			addCriterion("aTitle like", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleNotLike(String value) {
			addCriterion("aTitle not like", value, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleIn(List<String> values) {
			addCriterion("aTitle in", values, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleNotIn(List<String> values) {
			addCriterion("aTitle not in", values, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleBetween(String value1, String value2) {
			addCriterion("aTitle between", value1, value2, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtitleNotBetween(String value1, String value2) {
			addCriterion("aTitle not between", value1, value2, "atitle");
			return (Criteria) this;
		}

		public Criteria andAtagIsNull() {
			addCriterion("aTag is null");
			return (Criteria) this;
		}

		public Criteria andAtagIsNotNull() {
			addCriterion("aTag is not null");
			return (Criteria) this;
		}

		public Criteria andAtagEqualTo(String value) {
			addCriterion("aTag =", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagNotEqualTo(String value) {
			addCriterion("aTag <>", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagGreaterThan(String value) {
			addCriterion("aTag >", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagGreaterThanOrEqualTo(String value) {
			addCriterion("aTag >=", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagLessThan(String value) {
			addCriterion("aTag <", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagLessThanOrEqualTo(String value) {
			addCriterion("aTag <=", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagLike(String value) {
			addCriterion("aTag like", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagNotLike(String value) {
			addCriterion("aTag not like", value, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagIn(List<String> values) {
			addCriterion("aTag in", values, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagNotIn(List<String> values) {
			addCriterion("aTag not in", values, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagBetween(String value1, String value2) {
			addCriterion("aTag between", value1, value2, "atag");
			return (Criteria) this;
		}

		public Criteria andAtagNotBetween(String value1, String value2) {
			addCriterion("aTag not between", value1, value2, "atag");
			return (Criteria) this;
		}

		public Criteria andAtypeIsNull() {
			addCriterion("aType is null");
			return (Criteria) this;
		}

		public Criteria andAtypeIsNotNull() {
			addCriterion("aType is not null");
			return (Criteria) this;
		}

		public Criteria andAtypeEqualTo(String value) {
			addCriterion("aType =", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeNotEqualTo(String value) {
			addCriterion("aType <>", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeGreaterThan(String value) {
			addCriterion("aType >", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeGreaterThanOrEqualTo(String value) {
			addCriterion("aType >=", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeLessThan(String value) {
			addCriterion("aType <", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeLessThanOrEqualTo(String value) {
			addCriterion("aType <=", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeLike(String value) {
			addCriterion("aType like", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeNotLike(String value) {
			addCriterion("aType not like", value, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeIn(List<String> values) {
			addCriterion("aType in", values, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeNotIn(List<String> values) {
			addCriterion("aType not in", values, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeBetween(String value1, String value2) {
			addCriterion("aType between", value1, value2, "atype");
			return (Criteria) this;
		}

		public Criteria andAtypeNotBetween(String value1, String value2) {
			addCriterion("aType not between", value1, value2, "atype");
			return (Criteria) this;
		}

		public Criteria andAstructureIsNull() {
			addCriterion("aStructure is null");
			return (Criteria) this;
		}

		public Criteria andAstructureIsNotNull() {
			addCriterion("aStructure is not null");
			return (Criteria) this;
		}

		public Criteria andAstructureEqualTo(Integer value) {
			addCriterion("aStructure =", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureNotEqualTo(Integer value) {
			addCriterion("aStructure <>", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureGreaterThan(Integer value) {
			addCriterion("aStructure >", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureGreaterThanOrEqualTo(Integer value) {
			addCriterion("aStructure >=", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureLessThan(Integer value) {
			addCriterion("aStructure <", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureLessThanOrEqualTo(Integer value) {
			addCriterion("aStructure <=", value, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureIn(List<Integer> values) {
			addCriterion("aStructure in", values, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureNotIn(List<Integer> values) {
			addCriterion("aStructure not in", values, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureBetween(Integer value1, Integer value2) {
			addCriterion("aStructure between", value1, value2, "astructure");
			return (Criteria) this;
		}

		public Criteria andAstructureNotBetween(Integer value1, Integer value2) {
			addCriterion("aStructure not between", value1, value2, "astructure");
			return (Criteria) this;
		}

		public Criteria andAsourceIsNull() {
			addCriterion("aSource is null");
			return (Criteria) this;
		}

		public Criteria andAsourceIsNotNull() {
			addCriterion("aSource is not null");
			return (Criteria) this;
		}

		public Criteria andAsourceEqualTo(String value) {
			addCriterion("aSource =", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceNotEqualTo(String value) {
			addCriterion("aSource <>", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceGreaterThan(String value) {
			addCriterion("aSource >", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceGreaterThanOrEqualTo(String value) {
			addCriterion("aSource >=", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceLessThan(String value) {
			addCriterion("aSource <", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceLessThanOrEqualTo(String value) {
			addCriterion("aSource <=", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceLike(String value) {
			addCriterion("aSource like", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceNotLike(String value) {
			addCriterion("aSource not like", value, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceIn(List<String> values) {
			addCriterion("aSource in", values, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceNotIn(List<String> values) {
			addCriterion("aSource not in", values, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceBetween(String value1, String value2) {
			addCriterion("aSource between", value1, value2, "asource");
			return (Criteria) this;
		}

		public Criteria andAsourceNotBetween(String value1, String value2) {
			addCriterion("aSource not between", value1, value2, "asource");
			return (Criteria) this;
		}

		public Criteria andAshowcountIsNull() {
			addCriterion("aShowCount is null");
			return (Criteria) this;
		}

		public Criteria andAshowcountIsNotNull() {
			addCriterion("aShowCount is not null");
			return (Criteria) this;
		}

		public Criteria andAshowcountEqualTo(Long value) {
			addCriterion("aShowCount =", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountNotEqualTo(Long value) {
			addCriterion("aShowCount <>", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountGreaterThan(Long value) {
			addCriterion("aShowCount >", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountGreaterThanOrEqualTo(Long value) {
			addCriterion("aShowCount >=", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountLessThan(Long value) {
			addCriterion("aShowCount <", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountLessThanOrEqualTo(Long value) {
			addCriterion("aShowCount <=", value, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountIn(List<Long> values) {
			addCriterion("aShowCount in", values, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountNotIn(List<Long> values) {
			addCriterion("aShowCount not in", values, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountBetween(Long value1, Long value2) {
			addCriterion("aShowCount between", value1, value2, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAshowcountNotBetween(Long value1, Long value2) {
			addCriterion("aShowCount not between", value1, value2, "ashowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountIsNull() {
			addCriterion("aTrueShowCount is null");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountIsNotNull() {
			addCriterion("aTrueShowCount is not null");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountEqualTo(Long value) {
			addCriterion("aTrueShowCount =", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountNotEqualTo(Long value) {
			addCriterion("aTrueShowCount <>", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountGreaterThan(Long value) {
			addCriterion("aTrueShowCount >", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountGreaterThanOrEqualTo(Long value) {
			addCriterion("aTrueShowCount >=", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountLessThan(Long value) {
			addCriterion("aTrueShowCount <", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountLessThanOrEqualTo(Long value) {
			addCriterion("aTrueShowCount <=", value, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountIn(List<Long> values) {
			addCriterion("aTrueShowCount in", values, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountNotIn(List<Long> values) {
			addCriterion("aTrueShowCount not in", values, "atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountBetween(Long value1, Long value2) {
			addCriterion("aTrueShowCount between", value1, value2,
					"atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAtrueshowcountNotBetween(Long value1, Long value2) {
			addCriterion("aTrueShowCount not between", value1, value2,
					"atrueshowcount");
			return (Criteria) this;
		}

		public Criteria andAstatusIsNull() {
			addCriterion("aStatus is null");
			return (Criteria) this;
		}

		public Criteria andAstatusIsNotNull() {
			addCriterion("aStatus is not null");
			return (Criteria) this;
		}

		public Criteria andAstatusEqualTo(Integer value) {
			addCriterion("aStatus =", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusNotEqualTo(Integer value) {
			addCriterion("aStatus <>", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusGreaterThan(Integer value) {
			addCriterion("aStatus >", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("aStatus >=", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusLessThan(Integer value) {
			addCriterion("aStatus <", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusLessThanOrEqualTo(Integer value) {
			addCriterion("aStatus <=", value, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusIn(List<Integer> values) {
			addCriterion("aStatus in", values, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusNotIn(List<Integer> values) {
			addCriterion("aStatus not in", values, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusBetween(Integer value1, Integer value2) {
			addCriterion("aStatus between", value1, value2, "astatus");
			return (Criteria) this;
		}

		public Criteria andAstatusNotBetween(Integer value1, Integer value2) {
			addCriterion("aStatus not between", value1, value2, "astatus");
			return (Criteria) this;
		}

		public Criteria andAauthornameIsNull() {
			addCriterion("aAuthorName is null");
			return (Criteria) this;
		}

		public Criteria andAauthornameIsNotNull() {
			addCriterion("aAuthorName is not null");
			return (Criteria) this;
		}

		public Criteria andAauthornameEqualTo(String value) {
			addCriterion("aAuthorName =", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameNotEqualTo(String value) {
			addCriterion("aAuthorName <>", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameGreaterThan(String value) {
			addCriterion("aAuthorName >", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameGreaterThanOrEqualTo(String value) {
			addCriterion("aAuthorName >=", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameLessThan(String value) {
			addCriterion("aAuthorName <", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameLessThanOrEqualTo(String value) {
			addCriterion("aAuthorName <=", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameLike(String value) {
			addCriterion("aAuthorName like", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameNotLike(String value) {
			addCriterion("aAuthorName not like", value, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameIn(List<String> values) {
			addCriterion("aAuthorName in", values, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameNotIn(List<String> values) {
			addCriterion("aAuthorName not in", values, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameBetween(String value1, String value2) {
			addCriterion("aAuthorName between", value1, value2, "aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthornameNotBetween(String value1, String value2) {
			addCriterion("aAuthorName not between", value1, value2,
					"aauthorname");
			return (Criteria) this;
		}

		public Criteria andAauthorIsNull() {
			addCriterion("aAuthor is null");
			return (Criteria) this;
		}

		public Criteria andAauthorIsNotNull() {
			addCriterion("aAuthor is not null");
			return (Criteria) this;
		}

		public Criteria andAauthorEqualTo(String value) {
			addCriterion("aAuthor =", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorNotEqualTo(String value) {
			addCriterion("aAuthor <>", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorGreaterThan(String value) {
			addCriterion("aAuthor >", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorGreaterThanOrEqualTo(String value) {
			addCriterion("aAuthor >=", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorLessThan(String value) {
			addCriterion("aAuthor <", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorLessThanOrEqualTo(String value) {
			addCriterion("aAuthor <=", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorLike(String value) {
			addCriterion("aAuthor like", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorNotLike(String value) {
			addCriterion("aAuthor not like", value, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorIn(List<String> values) {
			addCriterion("aAuthor in", values, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorNotIn(List<String> values) {
			addCriterion("aAuthor not in", values, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorBetween(String value1, String value2) {
			addCriterion("aAuthor between", value1, value2, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAauthorNotBetween(String value1, String value2) {
			addCriterion("aAuthor not between", value1, value2, "aauthor");
			return (Criteria) this;
		}

		public Criteria andAimageIsNull() {
			addCriterion("aImage is null");
			return (Criteria) this;
		}

		public Criteria andAimageIsNotNull() {
			addCriterion("aImage is not null");
			return (Criteria) this;
		}

		public Criteria andAimageEqualTo(Long value) {
			addCriterion("aImage =", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageNotEqualTo(Long value) {
			addCriterion("aImage <>", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageGreaterThan(Long value) {
			addCriterion("aImage >", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageGreaterThanOrEqualTo(Long value) {
			addCriterion("aImage >=", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageLessThan(Long value) {
			addCriterion("aImage <", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageLessThanOrEqualTo(Long value) {
			addCriterion("aImage <=", value, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageIn(List<Long> values) {
			addCriterion("aImage in", values, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageNotIn(List<Long> values) {
			addCriterion("aImage not in", values, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageBetween(Long value1, Long value2) {
			addCriterion("aImage between", value1, value2, "aimage");
			return (Criteria) this;
		}

		public Criteria andAimageNotBetween(Long value1, Long value2) {
			addCriterion("aImage not between", value1, value2, "aimage");
			return (Criteria) this;
		}

		public Criteria andIsindexIsNull() {
			addCriterion("isIndex is null");
			return (Criteria) this;
		}

		public Criteria andIsindexIsNotNull() {
			addCriterion("isIndex is not null");
			return (Criteria) this;
		}

		public Criteria andIsindexEqualTo(Integer value) {
			addCriterion("isIndex =", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexNotEqualTo(Integer value) {
			addCriterion("isIndex <>", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexGreaterThan(Integer value) {
			addCriterion("isIndex >", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexGreaterThanOrEqualTo(Integer value) {
			addCriterion("isIndex >=", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexLessThan(Integer value) {
			addCriterion("isIndex <", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexLessThanOrEqualTo(Integer value) {
			addCriterion("isIndex <=", value, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexIn(List<Integer> values) {
			addCriterion("isIndex in", values, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexNotIn(List<Integer> values) {
			addCriterion("isIndex not in", values, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexBetween(Integer value1, Integer value2) {
			addCriterion("isIndex between", value1, value2, "isindex");
			return (Criteria) this;
		}

		public Criteria andIsindexNotBetween(Integer value1, Integer value2) {
			addCriterion("isIndex not between", value1, value2, "isindex");
			return (Criteria) this;
		}

		public Criteria andAorderIsNull() {
			addCriterion("aOrder is null");
			return (Criteria) this;
		}

		public Criteria andAorderIsNotNull() {
			addCriterion("aOrder is not null");
			return (Criteria) this;
		}

		public Criteria andAorderEqualTo(Long value) {
			addCriterion("aOrder =", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderNotEqualTo(Long value) {
			addCriterion("aOrder <>", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderGreaterThan(Long value) {
			addCriterion("aOrder >", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderGreaterThanOrEqualTo(Long value) {
			addCriterion("aOrder >=", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderLessThan(Long value) {
			addCriterion("aOrder <", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderLessThanOrEqualTo(Long value) {
			addCriterion("aOrder <=", value, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderIn(List<Long> values) {
			addCriterion("aOrder in", values, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderNotIn(List<Long> values) {
			addCriterion("aOrder not in", values, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderBetween(Long value1, Long value2) {
			addCriterion("aOrder between", value1, value2, "aorder");
			return (Criteria) this;
		}

		public Criteria andAorderNotBetween(Long value1, Long value2) {
			addCriterion("aOrder not between", value1, value2, "aorder");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createDate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createDate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createDate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createDate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createDate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createDate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createDate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createDate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createDate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createDate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createDate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNull() {
			addCriterion("updateDate is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNotNull() {
			addCriterion("updateDate is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateEqualTo(Date value) {
			addCriterion("updateDate =", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotEqualTo(Date value) {
			addCriterion("updateDate <>", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThan(Date value) {
			addCriterion("updateDate >", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("updateDate >=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThan(Date value) {
			addCriterion("updateDate <", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
			addCriterion("updateDate <=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIn(List<Date> values) {
			addCriterion("updateDate in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotIn(List<Date> values) {
			addCriterion("updateDate not in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateBetween(Date value1, Date value2) {
			addCriterion("updateDate between", value1, value2, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
			addCriterion("updateDate not between", value1, value2, "updatedate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblarticle
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 26 23:38:11 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}