package com.jybar.web.entity;

import java.util.Date;

public class TblBarUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_tid
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private Long userTid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_type
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private int userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_account
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_nickname
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_password
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_randomkey
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userRandomkey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_phone
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_email
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_status
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private int userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_createDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private Date userCreatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_updateDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private Date userUpdatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblbaruser.user_lastLoginDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	private Date userLastlogindate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_tid
	 * @return  the value of tblbaruser.user_tid
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public Long getUserTid() {
		return userTid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_tid
	 * @param userTid  the value for tblbaruser.user_tid
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserTid(Long userTid) {
		this.userTid = userTid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_type
	 * @return  the value of tblbaruser.user_type
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public int getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_type
	 * @param userType  the value for tblbaruser.user_type
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserType(int userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_account
	 * @return  the value of tblbaruser.user_account
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_account
	 * @param userAccount  the value for tblbaruser.user_account
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount == null ? null : userAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_nickname
	 * @return  the value of tblbaruser.user_nickname
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserNickname() {
		return userNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_nickname
	 * @param userNickname  the value for tblbaruser.user_nickname
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname == null ? null : userNickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_password
	 * @return  the value of tblbaruser.user_password
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_password
	 * @param userPassword  the value for tblbaruser.user_password
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword == null ? null : userPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_randomkey
	 * @return  the value of tblbaruser.user_randomkey
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserRandomkey() {
		return userRandomkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_randomkey
	 * @param userRandomkey  the value for tblbaruser.user_randomkey
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserRandomkey(String userRandomkey) {
		this.userRandomkey = userRandomkey == null ? null : userRandomkey
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_phone
	 * @return  the value of tblbaruser.user_phone
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_phone
	 * @param userPhone  the value for tblbaruser.user_phone
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone == null ? null : userPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_email
	 * @return  the value of tblbaruser.user_email
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_email
	 * @param userEmail  the value for tblbaruser.user_email
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_status
	 * @return  the value of tblbaruser.user_status
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public int getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_status
	 * @param userStatus  the value for tblbaruser.user_status
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_createDate
	 * @return  the value of tblbaruser.user_createDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public Date getUserCreatedate() {
		return userCreatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_createDate
	 * @param userCreatedate  the value for tblbaruser.user_createDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserCreatedate(Date userCreatedate) {
		this.userCreatedate = userCreatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_updateDate
	 * @return  the value of tblbaruser.user_updateDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public Date getUserUpdatedate() {
		return userUpdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_updateDate
	 * @param userUpdatedate  the value for tblbaruser.user_updateDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserUpdatedate(Date userUpdatedate) {
		this.userUpdatedate = userUpdatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblbaruser.user_lastLoginDate
	 * @return  the value of tblbaruser.user_lastLoginDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public Date getUserLastlogindate() {
		return userLastlogindate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblbaruser.user_lastLoginDate
	 * @param userLastlogindate  the value for tblbaruser.user_lastLoginDate
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	public void setUserLastlogindate(Date userLastlogindate) {
		this.userLastlogindate = userLastlogindate;
	}
}