package com.jybar.web.entity;

public class TblConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblconfig.tid
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	private Long tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblconfig.paraName
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	private String paraname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblconfig.parakey
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	private String parakey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblconfig.paravalue
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	private String paravalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblconfig.content
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblconfig.tid
	 * @return  the value of tblconfig.tid
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public Long getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblconfig.tid
	 * @param tid  the value for tblconfig.tid
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setTid(Long tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblconfig.paraName
	 * @return  the value of tblconfig.paraName
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public String getParaname() {
		return paraname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblconfig.paraName
	 * @param paraname  the value for tblconfig.paraName
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setParaname(String paraname) {
		this.paraname = paraname == null ? null : paraname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblconfig.parakey
	 * @return  the value of tblconfig.parakey
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public String getParakey() {
		return parakey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblconfig.parakey
	 * @param parakey  the value for tblconfig.parakey
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setParakey(String parakey) {
		this.parakey = parakey == null ? null : parakey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblconfig.paravalue
	 * @return  the value of tblconfig.paravalue
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public String getParavalue() {
		return paravalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblconfig.paravalue
	 * @param paravalue  the value for tblconfig.paravalue
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setParavalue(String paravalue) {
		this.paravalue = paravalue == null ? null : paravalue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblconfig.content
	 * @return  the value of tblconfig.content
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblconfig.content
	 * @param content  the value for tblconfig.content
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}