package com.jybar.web.entity;

import java.util.ArrayList;
import java.util.List;

public class TblConfigExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public TblConfigExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTidIsNull() {
			addCriterion("tid is null");
			return (Criteria) this;
		}

		public Criteria andTidIsNotNull() {
			addCriterion("tid is not null");
			return (Criteria) this;
		}

		public Criteria andTidEqualTo(Long value) {
			addCriterion("tid =", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotEqualTo(Long value) {
			addCriterion("tid <>", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThan(Long value) {
			addCriterion("tid >", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThanOrEqualTo(Long value) {
			addCriterion("tid >=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThan(Long value) {
			addCriterion("tid <", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThanOrEqualTo(Long value) {
			addCriterion("tid <=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidIn(List<Long> values) {
			addCriterion("tid in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotIn(List<Long> values) {
			addCriterion("tid not in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidBetween(Long value1, Long value2) {
			addCriterion("tid between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotBetween(Long value1, Long value2) {
			addCriterion("tid not between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andParanameIsNull() {
			addCriterion("paraName is null");
			return (Criteria) this;
		}

		public Criteria andParanameIsNotNull() {
			addCriterion("paraName is not null");
			return (Criteria) this;
		}

		public Criteria andParanameEqualTo(String value) {
			addCriterion("paraName =", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameNotEqualTo(String value) {
			addCriterion("paraName <>", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameGreaterThan(String value) {
			addCriterion("paraName >", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameGreaterThanOrEqualTo(String value) {
			addCriterion("paraName >=", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameLessThan(String value) {
			addCriterion("paraName <", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameLessThanOrEqualTo(String value) {
			addCriterion("paraName <=", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameLike(String value) {
			addCriterion("paraName like", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameNotLike(String value) {
			addCriterion("paraName not like", value, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameIn(List<String> values) {
			addCriterion("paraName in", values, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameNotIn(List<String> values) {
			addCriterion("paraName not in", values, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameBetween(String value1, String value2) {
			addCriterion("paraName between", value1, value2, "paraname");
			return (Criteria) this;
		}

		public Criteria andParanameNotBetween(String value1, String value2) {
			addCriterion("paraName not between", value1, value2, "paraname");
			return (Criteria) this;
		}

		public Criteria andParakeyIsNull() {
			addCriterion("parakey is null");
			return (Criteria) this;
		}

		public Criteria andParakeyIsNotNull() {
			addCriterion("parakey is not null");
			return (Criteria) this;
		}

		public Criteria andParakeyEqualTo(String value) {
			addCriterion("parakey =", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyNotEqualTo(String value) {
			addCriterion("parakey <>", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyGreaterThan(String value) {
			addCriterion("parakey >", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyGreaterThanOrEqualTo(String value) {
			addCriterion("parakey >=", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyLessThan(String value) {
			addCriterion("parakey <", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyLessThanOrEqualTo(String value) {
			addCriterion("parakey <=", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyLike(String value) {
			addCriterion("parakey like", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyNotLike(String value) {
			addCriterion("parakey not like", value, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyIn(List<String> values) {
			addCriterion("parakey in", values, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyNotIn(List<String> values) {
			addCriterion("parakey not in", values, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyBetween(String value1, String value2) {
			addCriterion("parakey between", value1, value2, "parakey");
			return (Criteria) this;
		}

		public Criteria andParakeyNotBetween(String value1, String value2) {
			addCriterion("parakey not between", value1, value2, "parakey");
			return (Criteria) this;
		}

		public Criteria andParavalueIsNull() {
			addCriterion("paravalue is null");
			return (Criteria) this;
		}

		public Criteria andParavalueIsNotNull() {
			addCriterion("paravalue is not null");
			return (Criteria) this;
		}

		public Criteria andParavalueEqualTo(String value) {
			addCriterion("paravalue =", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueNotEqualTo(String value) {
			addCriterion("paravalue <>", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueGreaterThan(String value) {
			addCriterion("paravalue >", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueGreaterThanOrEqualTo(String value) {
			addCriterion("paravalue >=", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueLessThan(String value) {
			addCriterion("paravalue <", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueLessThanOrEqualTo(String value) {
			addCriterion("paravalue <=", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueLike(String value) {
			addCriterion("paravalue like", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueNotLike(String value) {
			addCriterion("paravalue not like", value, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueIn(List<String> values) {
			addCriterion("paravalue in", values, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueNotIn(List<String> values) {
			addCriterion("paravalue not in", values, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueBetween(String value1, String value2) {
			addCriterion("paravalue between", value1, value2, "paravalue");
			return (Criteria) this;
		}

		public Criteria andParavalueNotBetween(String value1, String value2) {
			addCriterion("paravalue not between", value1, value2, "paravalue");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblconfig
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 24 23:49:06 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}