package com.jybar.web.entity;

import java.util.Date;

public class TblFriendLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.tid
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.tType
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Integer ttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.tUrl
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private String turl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.fImage
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Long fimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.tContent
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private String tcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.tOrder
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Long torder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.createDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblfriendlink.updateDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.tid
     *
     * @return the value of tblfriendlink.tid
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.tid
     *
     * @param tid the value for tblfriendlink.tid
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.tType
     *
     * @return the value of tblfriendlink.tType
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Integer getTtype() {
        return ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.tType
     *
     * @param ttype the value for tblfriendlink.tType
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setTtype(Integer ttype) {
        this.ttype = ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.tUrl
     *
     * @return the value of tblfriendlink.tUrl
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public String getTurl() {
        return turl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.tUrl
     *
     * @param turl the value for tblfriendlink.tUrl
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setTurl(String turl) {
        this.turl = turl == null ? null : turl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.fImage
     *
     * @return the value of tblfriendlink.fImage
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Long getFimage() {
        return fimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.fImage
     *
     * @param fimage the value for tblfriendlink.fImage
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setFimage(Long fimage) {
        this.fimage = fimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.tContent
     *
     * @return the value of tblfriendlink.tContent
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public String getTcontent() {
        return tcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.tContent
     *
     * @param tcontent the value for tblfriendlink.tContent
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setTcontent(String tcontent) {
        this.tcontent = tcontent == null ? null : tcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.tOrder
     *
     * @return the value of tblfriendlink.tOrder
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Long getTorder() {
        return torder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.tOrder
     *
     * @param torder the value for tblfriendlink.tOrder
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setTorder(Long torder) {
        this.torder = torder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.createDate
     *
     * @return the value of tblfriendlink.createDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.createDate
     *
     * @param createdate the value for tblfriendlink.createDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblfriendlink.updateDate
     *
     * @return the value of tblfriendlink.updateDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblfriendlink.updateDate
     *
     * @param updatedate the value for tblfriendlink.updateDate
     *
     * @mbggenerated Mon Sep 08 11:59:49 CST 2014
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}