package com.jybar.web.entity;

import java.util.Date;

public class TblImage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tid
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private Long tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tType
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private Integer ttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tUrl
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private String turl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tContent
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private String tcontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tOrder
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private Long torder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.createDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.updateDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private Date updatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblimage.tByte
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	private byte[] tbyte;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tid
	 * @return  the value of tblimage.tid
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Long getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tid
	 * @param tid  the value for tblimage.tid
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTid(Long tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tType
	 * @return  the value of tblimage.tType
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Integer getTtype() {
		return ttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tType
	 * @param ttype  the value for tblimage.tType
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTtype(Integer ttype) {
		this.ttype = ttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tUrl
	 * @return  the value of tblimage.tUrl
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public String getTurl() {
		return turl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tUrl
	 * @param turl  the value for tblimage.tUrl
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTurl(String turl) {
		this.turl = turl == null ? null : turl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tContent
	 * @return  the value of tblimage.tContent
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public String getTcontent() {
		return tcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tContent
	 * @param tcontent  the value for tblimage.tContent
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTcontent(String tcontent) {
		this.tcontent = tcontent == null ? null : tcontent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tOrder
	 * @return  the value of tblimage.tOrder
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Long getTorder() {
		return torder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tOrder
	 * @param torder  the value for tblimage.tOrder
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTorder(Long torder) {
		this.torder = torder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.createDate
	 * @return  the value of tblimage.createDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.createDate
	 * @param createdate  the value for tblimage.createDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.updateDate
	 * @return  the value of tblimage.updateDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Date getUpdatedate() {
		return updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.updateDate
	 * @param updatedate  the value for tblimage.updateDate
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblimage.tByte
	 * @return  the value of tblimage.tByte
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public byte[] getTbyte() {
		return tbyte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblimage.tByte
	 * @param tbyte  the value for tblimage.tByte
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setTbyte(byte[] tbyte) {
		this.tbyte = tbyte;
	}
}