package com.jybar.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TblImageExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public TblImageExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTidIsNull() {
			addCriterion("tid is null");
			return (Criteria) this;
		}

		public Criteria andTidIsNotNull() {
			addCriterion("tid is not null");
			return (Criteria) this;
		}

		public Criteria andTidEqualTo(Long value) {
			addCriterion("tid =", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotEqualTo(Long value) {
			addCriterion("tid <>", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThan(Long value) {
			addCriterion("tid >", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThanOrEqualTo(Long value) {
			addCriterion("tid >=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThan(Long value) {
			addCriterion("tid <", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThanOrEqualTo(Long value) {
			addCriterion("tid <=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidIn(List<Long> values) {
			addCriterion("tid in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotIn(List<Long> values) {
			addCriterion("tid not in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidBetween(Long value1, Long value2) {
			addCriterion("tid between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotBetween(Long value1, Long value2) {
			addCriterion("tid not between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andTtypeIsNull() {
			addCriterion("tType is null");
			return (Criteria) this;
		}

		public Criteria andTtypeIsNotNull() {
			addCriterion("tType is not null");
			return (Criteria) this;
		}

		public Criteria andTtypeEqualTo(Integer value) {
			addCriterion("tType =", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeNotEqualTo(Integer value) {
			addCriterion("tType <>", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeGreaterThan(Integer value) {
			addCriterion("tType >", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("tType >=", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeLessThan(Integer value) {
			addCriterion("tType <", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeLessThanOrEqualTo(Integer value) {
			addCriterion("tType <=", value, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeIn(List<Integer> values) {
			addCriterion("tType in", values, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeNotIn(List<Integer> values) {
			addCriterion("tType not in", values, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeBetween(Integer value1, Integer value2) {
			addCriterion("tType between", value1, value2, "ttype");
			return (Criteria) this;
		}

		public Criteria andTtypeNotBetween(Integer value1, Integer value2) {
			addCriterion("tType not between", value1, value2, "ttype");
			return (Criteria) this;
		}

		public Criteria andTurlIsNull() {
			addCriterion("tUrl is null");
			return (Criteria) this;
		}

		public Criteria andTurlIsNotNull() {
			addCriterion("tUrl is not null");
			return (Criteria) this;
		}

		public Criteria andTurlEqualTo(String value) {
			addCriterion("tUrl =", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlNotEqualTo(String value) {
			addCriterion("tUrl <>", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlGreaterThan(String value) {
			addCriterion("tUrl >", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlGreaterThanOrEqualTo(String value) {
			addCriterion("tUrl >=", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlLessThan(String value) {
			addCriterion("tUrl <", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlLessThanOrEqualTo(String value) {
			addCriterion("tUrl <=", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlLike(String value) {
			addCriterion("tUrl like", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlNotLike(String value) {
			addCriterion("tUrl not like", value, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlIn(List<String> values) {
			addCriterion("tUrl in", values, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlNotIn(List<String> values) {
			addCriterion("tUrl not in", values, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlBetween(String value1, String value2) {
			addCriterion("tUrl between", value1, value2, "turl");
			return (Criteria) this;
		}

		public Criteria andTurlNotBetween(String value1, String value2) {
			addCriterion("tUrl not between", value1, value2, "turl");
			return (Criteria) this;
		}

		public Criteria andTcontentIsNull() {
			addCriterion("tContent is null");
			return (Criteria) this;
		}

		public Criteria andTcontentIsNotNull() {
			addCriterion("tContent is not null");
			return (Criteria) this;
		}

		public Criteria andTcontentEqualTo(String value) {
			addCriterion("tContent =", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentNotEqualTo(String value) {
			addCriterion("tContent <>", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentGreaterThan(String value) {
			addCriterion("tContent >", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentGreaterThanOrEqualTo(String value) {
			addCriterion("tContent >=", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentLessThan(String value) {
			addCriterion("tContent <", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentLessThanOrEqualTo(String value) {
			addCriterion("tContent <=", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentLike(String value) {
			addCriterion("tContent like", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentNotLike(String value) {
			addCriterion("tContent not like", value, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentIn(List<String> values) {
			addCriterion("tContent in", values, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentNotIn(List<String> values) {
			addCriterion("tContent not in", values, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentBetween(String value1, String value2) {
			addCriterion("tContent between", value1, value2, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTcontentNotBetween(String value1, String value2) {
			addCriterion("tContent not between", value1, value2, "tcontent");
			return (Criteria) this;
		}

		public Criteria andTorderIsNull() {
			addCriterion("tOrder is null");
			return (Criteria) this;
		}

		public Criteria andTorderIsNotNull() {
			addCriterion("tOrder is not null");
			return (Criteria) this;
		}

		public Criteria andTorderEqualTo(Long value) {
			addCriterion("tOrder =", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderNotEqualTo(Long value) {
			addCriterion("tOrder <>", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderGreaterThan(Long value) {
			addCriterion("tOrder >", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderGreaterThanOrEqualTo(Long value) {
			addCriterion("tOrder >=", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderLessThan(Long value) {
			addCriterion("tOrder <", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderLessThanOrEqualTo(Long value) {
			addCriterion("tOrder <=", value, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderIn(List<Long> values) {
			addCriterion("tOrder in", values, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderNotIn(List<Long> values) {
			addCriterion("tOrder not in", values, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderBetween(Long value1, Long value2) {
			addCriterion("tOrder between", value1, value2, "torder");
			return (Criteria) this;
		}

		public Criteria andTorderNotBetween(Long value1, Long value2) {
			addCriterion("tOrder not between", value1, value2, "torder");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createDate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createDate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createDate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createDate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createDate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createDate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createDate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createDate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createDate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createDate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createDate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNull() {
			addCriterion("updateDate is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIsNotNull() {
			addCriterion("updateDate is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedateEqualTo(Date value) {
			addCriterion("updateDate =", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotEqualTo(Date value) {
			addCriterion("updateDate <>", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThan(Date value) {
			addCriterion("updateDate >", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("updateDate >=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThan(Date value) {
			addCriterion("updateDate <", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
			addCriterion("updateDate <=", value, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateIn(List<Date> values) {
			addCriterion("updateDate in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotIn(List<Date> values) {
			addCriterion("updateDate not in", values, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateBetween(Date value1, Date value2) {
			addCriterion("updateDate between", value1, value2, "updatedate");
			return (Criteria) this;
		}

		public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
			addCriterion("updateDate not between", value1, value2, "updatedate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblimage
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 27 21:37:37 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}