package com.jybar.web.entity;

import java.util.Date;

public class TblUrlResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.tid
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Long tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.urlType
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer urltype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.urlName
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private String urlname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.url
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.urlStatus
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer urlstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.urlOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer urlorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.sortWeight
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer sortweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.isShowIndex
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer isshowindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.clickCount
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Long clickcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.clickCountTrue
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Long clickcounttrue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.clickOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer clickorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.createDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.updateDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Date updatedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tblurlresource.isRed
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	private Integer isred;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.tid
	 * @return  the value of tblurlresource.tid
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Long getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.tid
	 * @param tid  the value for tblurlresource.tid
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setTid(Long tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.urlType
	 * @return  the value of tblurlresource.urlType
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getUrltype() {
		return urltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.urlType
	 * @param urltype  the value for tblurlresource.urlType
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUrltype(Integer urltype) {
		this.urltype = urltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.urlName
	 * @return  the value of tblurlresource.urlName
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public String getUrlname() {
		return urlname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.urlName
	 * @param urlname  the value for tblurlresource.urlName
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUrlname(String urlname) {
		this.urlname = urlname == null ? null : urlname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.url
	 * @return  the value of tblurlresource.url
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.url
	 * @param url  the value for tblurlresource.url
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.urlStatus
	 * @return  the value of tblurlresource.urlStatus
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getUrlstatus() {
		return urlstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.urlStatus
	 * @param urlstatus  the value for tblurlresource.urlStatus
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUrlstatus(Integer urlstatus) {
		this.urlstatus = urlstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.urlOrder
	 * @return  the value of tblurlresource.urlOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getUrlorder() {
		return urlorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.urlOrder
	 * @param urlorder  the value for tblurlresource.urlOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUrlorder(Integer urlorder) {
		this.urlorder = urlorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.sortWeight
	 * @return  the value of tblurlresource.sortWeight
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getSortweight() {
		return sortweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.sortWeight
	 * @param sortweight  the value for tblurlresource.sortWeight
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setSortweight(Integer sortweight) {
		this.sortweight = sortweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.isShowIndex
	 * @return  the value of tblurlresource.isShowIndex
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getIsshowindex() {
		return isshowindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.isShowIndex
	 * @param isshowindex  the value for tblurlresource.isShowIndex
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setIsshowindex(Integer isshowindex) {
		this.isshowindex = isshowindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.clickCount
	 * @return  the value of tblurlresource.clickCount
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Long getClickcount() {
		return clickcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.clickCount
	 * @param clickcount  the value for tblurlresource.clickCount
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setClickcount(Long clickcount) {
		this.clickcount = clickcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.clickCountTrue
	 * @return  the value of tblurlresource.clickCountTrue
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Long getClickcounttrue() {
		return clickcounttrue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.clickCountTrue
	 * @param clickcounttrue  the value for tblurlresource.clickCountTrue
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setClickcounttrue(Long clickcounttrue) {
		this.clickcounttrue = clickcounttrue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.clickOrder
	 * @return  the value of tblurlresource.clickOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getClickorder() {
		return clickorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.clickOrder
	 * @param clickorder  the value for tblurlresource.clickOrder
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setClickorder(Integer clickorder) {
		this.clickorder = clickorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.createDate
	 * @return  the value of tblurlresource.createDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.createDate
	 * @param createdate  the value for tblurlresource.createDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.updateDate
	 * @return  the value of tblurlresource.updateDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Date getUpdatedate() {
		return updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.updateDate
	 * @param updatedate  the value for tblurlresource.updateDate
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tblurlresource.isRed
	 * @return  the value of tblurlresource.isRed
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public Integer getIsred() {
		return isred;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tblurlresource.isRed
	 * @param isred  the value for tblurlresource.isRed
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	public void setIsred(Integer isred) {
		this.isred = isred;
	}
}