package com.jybar.web.mapper;

import com.jybar.web.entity.TblArticle;
import com.jybar.web.entity.TblArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblArticleMapper extends SqlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int countByExample(TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int deleteByExample(TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int deleteByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int insert(TblArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int insertSelective(TblArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	List<TblArticle> selectByExampleWithBLOBs(TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	List<TblArticle> selectByExample(TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	TblArticle selectByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TblArticle record,
			@Param("example") TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TblArticle record,
			@Param("example") TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExample(@Param("record") TblArticle record,
			@Param("example") TblArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKeySelective(TblArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TblArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblarticle
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKey(TblArticle record);
}