package com.jybar.web.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jybar.web.entity.TblBarUser;
import com.jybar.web.entity.TblBarUserExample;
import com.jybar.web.util.Page;

public interface TblBarUserMapper extends SqlMapper{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int countByExample(TblBarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int deleteByExample(TblBarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int deleteByPrimaryKey(Long userTid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int insert(TblBarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int insertSelective(TblBarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	List<TblBarUser> selectByExample(TblBarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	TblBarUser selectByPrimaryKey(Long userTid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TblBarUser record,
			@Param("example") TblBarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int updateByExample(@Param("record") TblBarUser record,
			@Param("example") TblBarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int updateByPrimaryKeySelective(TblBarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblbaruser
	 * @mbggenerated  Sat Jul 05 20:13:21 CST 2014
	 */
	int updateByPrimaryKey(TblBarUser record);

	TblBarUser selectByAccountAndPswd(@Param("account") String account,@Param("pswd") String pswd,@Param("type") int type);
    
    String selectRandomkeyByAccountAndType(@Param("account") String account,@Param("type") int type);
    
    List<TblBarUser> queryAllUser(Page page);
}