package com.jybar.web.mapper;

import com.jybar.web.entity.TblConfig;
import com.jybar.web.entity.TblConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblConfigMapper extends SqlMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int countByExample(TblConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int deleteByExample(TblConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int deleteByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int insert(TblConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int insertSelective(TblConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	List<TblConfig> selectByExample(TblConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	TblConfig selectByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TblConfig record,
			@Param("example") TblConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int updateByExample(@Param("record") TblConfig record,
			@Param("example") TblConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int updateByPrimaryKeySelective(TblConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblconfig
	 * @mbggenerated  Mon Aug 25 00:39:30 CST 2014
	 */
	int updateByPrimaryKey(TblConfig record);
}