package com.jybar.web.mapper;

import com.jybar.web.entity.TblImage;
import com.jybar.web.entity.TblImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblImageMapper  extends SqlMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int countByExample(TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int deleteByExample(TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int deleteByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int insert(TblImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int insertSelective(TblImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	List<TblImage> selectByExampleWithBLOBs(TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	List<TblImage> selectByExample(TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	TblImage selectByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TblImage record,
			@Param("example") TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TblImage record,
			@Param("example") TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByExample(@Param("record") TblImage record,
			@Param("example") TblImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKeySelective(TblImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TblImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblimage
	 * @mbggenerated  Sun Sep 07 22:38:26 CST 2014
	 */
	int updateByPrimaryKey(TblImage record);
}