package com.jybar.web.mapper;

import com.jybar.web.entity.TblUrlResource;
import com.jybar.web.entity.TblUrlResourceExample;
import com.jybar.web.util.Page;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblUrlResourceMapper extends SqlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int countByExample(TblUrlResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int deleteByExample(TblUrlResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int deleteByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int insert(TblUrlResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int insertSelective(TblUrlResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	List<TblUrlResource> selectByExample(TblUrlResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	TblUrlResource selectByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TblUrlResource record,
			@Param("example") TblUrlResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int updateByExample(@Param("record") TblUrlResource record,
			@Param("example") TblUrlResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int updateByPrimaryKeySelective(TblUrlResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tblurlresource
	 * @mbggenerated  Sun Aug 24 22:57:48 CST 2014
	 */
	int updateByPrimaryKey(TblUrlResource record);

}